In [1]:
import pandas as pd
import numpy as np
import os
import re

In [2]:
PATH = "/Users/tboudreaux/SAOSummer2018/simulations/externalSimulations/TestSimulations/compileTest/N3k_K_T1000"

In [3]:
files = [x for x in os.listdir(PATH) if x[0] != '.']

In [4]:
bev = [f"{PATH}/{x}" for x in files if 'bev.82_' in x]
lagr = [f"{PATH}/{x}" for x in files if x == "lagr.7"][0]

In [5]:
with open(lagr, 'r') as f:
    lagr_lines = f.readlines()

In [6]:
tlagr = [x.split() for x in lagr_lines[2:10]]

In [7]:
len(tlagr[3])

284

In [8]:
header_line = lagr_lines[0]

In [9]:
header_line

'## Time, [Column number | Label]:    2 R_{lagr}   21 R_{lagr,s}   39 R_{lagr,b}   57 <M>   76 N_{shell}   95 <V_x>  114 <V_y>  133 <V_z>  152<V>  171 <V_r>  190 <V_t>  209 \\Sigma^2  228 \\Sigma_r^2  247 \\Sigma_t^2  266 <V_{rot.}> (All units are NB)\n'

In [10]:
parsed_header = [x.split() if len(x.split()) != 1 else x.split('<') for x in re.split(r'\s{2,}', header_line.split(':')[1])[1:]]

In [11]:
parsed_header

[['2', 'R_{lagr}'],
 ['21', 'R_{lagr,s}'],
 ['39', 'R_{lagr,b}'],
 ['57', '<M>'],
 ['76', 'N_{shell}'],
 ['95', '<V_x>'],
 ['114', '<V_y>'],
 ['133', '<V_z>'],
 ['152', 'V>'],
 ['171', '<V_r>'],
 ['190', '<V_t>'],
 ['209', '\\Sigma^2'],
 ['228', '\\Sigma_r^2'],
 ['247', '\\Sigma_t^2'],
 ['266', '<V_{rot.}>', '(All', 'units', 'are', 'NB)']]

In [12]:
line_starts = [int(x[0]) for x in parsed_header]
line_starts.insert(0, 1)
line_starts.insert(-1, 285)
line_labels = [x[1].strip('<').strip('>').strip('\\') for x in parsed_header]
line_labels.insert(0, 'Time')

In [13]:
print(line_labels)
print(line_starts)

['Time', 'R_{lagr}', 'R_{lagr,s}', 'R_{lagr,b}', 'M', 'N_{shell}', 'V_x', 'V_y', 'V_z', 'V', 'V_r', 'V_t', 'Sigma^2', 'Sigma_r^2', 'Sigma_t^2', 'V_{rot.}']
[1, 2, 21, 39, 57, 76, 95, 114, 133, 152, 171, 190, 209, 228, 247, 285, 266]

In [14]:
full_labels = list()
running_sum = 0
for start, end, label in zip(line_starts, line_starts[1:], line_labels):
    lines = [f"{label}_{i}" for i, n in enumerate(range(start, end))]
    running_sum += len(lines)
    full_labels.extend(lines)
print(running_sum)

284

In [17]:
df = pd.read_csv(lagr, sep=r'\s+', engine='python', names=full_labels, skiprows=2)

In [21]:
df[['Time_0', "R_{lagr}_0"]]

           Time_0  R_{lagr}_0
0        0.000000    0.095285
1        0.500122    0.115665
2        1.000000    0.062233
3        1.500244    0.097731
4        2.000000    0.069478
5        2.500244    0.100412
6        3.000000    0.075922
7        3.500244    0.085374
8        4.000000    0.080554
9        4.500244    0.058592
10       5.000000    0.094649
11       5.500122    0.064525
12       6.000000    0.047796
13       6.500244    0.123284
14       7.000000    0.099823
15       7.500244    0.096640
16       8.000000    0.123669
17       8.500244    0.098623
18       9.000000    0.062152
19       9.500488    0.095759
20      10.000000    0.067449
21      10.500244    0.076966
22      11.000000    0.100195
23      11.500244    0.065713
24      12.000000    0.086725
25      12.500122    0.096456
26      13.000000    0.091103
27      13.500122    0.086862
28      14.000000    0.101723
29      14.500488    0.055821
...           ...         ...
1971   985.501953    0.174432
1972   986.000000    0.135716
1973   986.500244    0.092180
1974   987.000000    0.192620
1975   987.501953    0.190848
1976   988.000000    0.185510
1977   988.503906    0.075872
1978   989.000000    0.064782
1979   989.503906    0.138250
1980   990.000000    0.163011
1981   990.501953    0.152008
1982   991.000000    0.198779
1983   991.503906    0.214394
1984   992.000000    0.197136
1985   992.501953    0.152378
1986   993.000000    0.188319
1987   993.501953    0.181302
1988   994.000000    0.096503
1989   994.500977    0.099606
1990   995.000000    0.124885
1991   995.500977    0.149212
1992   996.000000    0.165097
1993   996.503906    0.094464
1994   997.000000    0.131274
1995   997.501953    0.208296
1996   998.000000    0.156682
1997   998.501953    0.203735
1998   999.000000    0.198072
1999   999.501953    0.194903
2000  1000.000000    0.101666

[2001 rows x 2 columns]